"""ARSENAL (armas especiales), Monedas Lunares en campaña y RANKING por ubicación.
Uso: python3 test/arsenal.py"""
import os, sys, time
from playwright.sync_api import sync_playwright
sys.path.insert(0, os.path.dirname(__file__))
from smoke import OUT, ARGS
from pvp import serve, st, wait, MOCK, check, RESULTS

def main():
    srv = serve()
    url = 'http://127.0.0.1:%d/index.html' % srv.server_address[1]
    with sync_playwright() as pw:
        b = pw.chromium.launch(args=ARGS)
        ctx = b.new_context(viewport={'width': 390, 'height': 844}, is_mobile=True, has_touch=True, timezone_id='America/Argentina/Cordoba')
        ctx.add_init_script(MOCK)
        errs = []
        def mk():
            p = ctx.new_page()
            p.on('pageerror', lambda e: errs.append(str(e)))
            p.goto(url)
            p.wait_for_function('window.__BB_READY === true', timeout=30000)
            p.click('#btn-start'); p.wait_for_timeout(300)
            return p
        A = mk()
        check('menú con ARSENAL y RANKING', A.is_visible('#btn-arsenal') and A.is_visible('#btn-rank'))
        A.screenshot(path=OUT + '/a0_menu.png')
        # --- arsenal ---
        A.click('#btn-arsenal'); A.wait_for_timeout(400)
        check('pantalla de arsenal con 16 armas', A.is_visible('#s-arsenal') and A.evaluate("document.querySelectorAll('#ars-list .ars-item').length") == 16)
        check('4 armas gratis (una por tipo)', A.evaluate("Object.keys(BB.game.arsenal.data.owned).sort().join()") == 'cryo,magnet,nova,repair')
        check('set inicial de 3 armas', A.evaluate('BB.game.arsenal.set().join()') == 'nova,cryo,repair')
        A.screenshot(path=OUT + '/a1_arsenal.png')
        A.evaluate('BB.game.save.data.coins = 20000'); A.evaluate('BB.game.arsenal.render()')
        A.click('button[data-act="buy"][data-id="rain"]'); A.wait_for_timeout(200)
        check('comprar Lluvia de Plasma con monedas', A.evaluate("BB.game.arsenal.lvl('rain')") == 1 and A.evaluate('BB.game.save.data.coins') == 18500)
        A.evaluate('BB.game.cup.data.ml = 5000')
        A.click('button[data-act="buy"][data-id="hole"]'); A.wait_for_timeout(200)
        check('Agujero Negro se compra con monedas (4.500)', A.evaluate("BB.game.arsenal.lvl('hole')") == 1 and A.evaluate('BB.game.save.data.coins') == 14000)
        check('las Monedas Lunares no se tocan en campaña', A.evaluate('BB.game.cup.data.ml') == 5000)
        check('el arsenal no ofrece pagar con ML', A.query_selector('#ars-pay') is None and '#i-moon' not in A.inner_html('#ars-list'))
        A.click('button[data-act="up"][data-id="nova"]'); A.wait_for_timeout(200)
        check('mejorar arma con monedas (300)', A.evaluate("BB.game.arsenal.lvl('nova')") == 2 and A.evaluate('BB.game.save.data.coins') == 13700)
        A.click('button[data-act="up"][data-id="cryo"]'); A.wait_for_timeout(200)
        check('segunda mejora con monedas', A.evaluate("BB.game.arsenal.lvl('cryo')") == 2 and A.evaluate('BB.game.save.data.coins') == 13400)
        A.click('#ars-slots [data-slot="2"]'); A.wait_for_timeout(100)
        A.click('button[data-act="eq"][data-id="rain"]'); A.wait_for_timeout(200)
        check('equipar en el casillero elegido', A.evaluate('BB.game.arsenal.set().join()') == 'nova,cryo,rain')
        check('muestra el tipo de build', 'OFENSIVO' in A.inner_text('#ars-build'), A.inner_text('#ars-build'))
        A.click('#ars-sets button[data-set="1"]'); A.wait_for_timeout(100)
        check('3 sets guardados, se cambia de set', A.evaluate('BB.game.arsenal.data.cur') == 1 and A.evaluate('BB.game.arsenal.set().join()') == 'nova,repair,magnet')
        A.click('#ars-sets button[data-set="0"]'); A.wait_for_timeout(100)
        A.click('#ars-filter button[data-f="def"]'); A.wait_for_timeout(100)
        check('filtro por tipo', A.evaluate("document.querySelectorAll('#ars-list .ars-item').length") == 4)
        A.click('#ars-filter button[data-f="all"]'); A.wait_for_timeout(100)
        A.screenshot(path=OUT + '/a2_arsenal_set.png')
        # --- tienda de campaña con ML ---
        A.click('#ars-back'); A.wait_for_timeout(200)
        A.click('#btn-shop'); A.wait_for_timeout(800)
        check('la tienda de campaña no ofrece pagar con ML', A.query_selector('#shop-pay') is None and '#i-moon' not in A.inner_html('#shop-items'))
        A.evaluate('BB.game.save.data.coins = 0; BB.game.ui.renderShop()')
        lv0 = A.evaluate('BB.game.save.data.shop.up.power || 0')
        A.click('button[data-buy="up_power"]'); A.wait_for_timeout(200)
        check('sin monedas no se mejora aunque tengas ML', A.evaluate('BB.game.save.data.shop.up.power || 0') == lv0 and A.evaluate('BB.game.cup.data.ml') == 5000)
        A.screenshot(path=OUT + '/a3_shop_ml.png')
        A.click('#shop-back'); A.wait_for_timeout(600)
        # --- en partida ---
        A.click('#btn-play'); A.wait_for_timeout(800)
        A.evaluate('BB.game.shields = 3')
        check('HUD muestra las 3 armas', A.is_visible('#h-arsenal') and A.evaluate("document.querySelectorAll('#h-arsenal .ars').length") == 3)
        ok = wait(lambda: A.evaluate('BB.game.meteors.countAlive()') > 0, 15)
        A.wait_for_timeout(1500)
        hp0 = A.evaluate('(()=>{let s=0; BB.game.meteors.forEachAlive(m=>s+=m.hp); return s})()')
        k0 = A.evaluate('BB.game.levelKills')
        A.click('#h-arsenal .ars >> nth=0'); A.wait_for_timeout(2500)
        hp1 = A.evaluate('(()=>{let s=0; BB.game.meteors.forEachAlive(m=>s+=m.hp); return s})()')
        check('Misil Nova sale, explota y daña', not A.evaluate('BB.game.arsenal.charges[0]') and (A.evaluate('BB.game.levelKills') > k0 or hp1 < hp0), (hp0, hp1))
        A.screenshot(path=OUT + '/a4_hud.png')
        A.click('#h-arsenal .ars >> nth=0'); A.wait_for_timeout(200)
        check('usada: no se puede volver a usar hasta el boss', not A.evaluate('BB.game.arsenal.charges[0]') and 'BOSS' in A.inner_text('#h-arsenal'))
        if st(A) == 'LEVEL_COMPLETE': A.click('#btn-next'); A.wait_for_timeout(800)
        A.evaluate('BB.game.shields = 3')
        wait(lambda: A.evaluate('BB.game.meteors.countAlive()') > 0 and st(A) == 'PLAYING', 15)
        A.evaluate("BB.game.arsenal.launch('cryo', BB.game.arsenal.bestTarget(), {dmg:1, R:30, freeze:8, speed:40, col:[.5,.85,1]})")
        ok = wait(lambda: A.evaluate('(()=>{let n=0; BB.game.meteors.forEachAlive(m=>{if(m.frozenT>0)n++}); return n})()') > 0, 6)
        check('Misil Criogénico congela', ok)
        A.screenshot(path=OUT + '/a5_frozen.png')
        A.evaluate('BB.game.shields = 1')
        A.evaluate('BB.game.arsenal.use(1)')   # cryo del set
        A.evaluate("BB.game.arsenal.data.sets[0][2] = 'repair'; BB.game.arsenal.renderHud()")
        A.evaluate('BB.game.arsenal.use(2)')
        check('Reparación recupera un escudo', A.evaluate('BB.game.shields') == 2)
        check('las 3 usadas', A.evaluate('BB.game.arsenal.charges.join()') == 'false,false,false')
        # boss -> recarga
        A.evaluate('BB.game.toMenu(); BB.game.camp().cycle = 0; BB.game.startRun(5); BB.game.shields = 99')
        wait(lambda: st(A) == 'BOSS_FIGHT', 20)
        A.evaluate('BB.game.arsenal.charges = [false,false,false]; BB.game.arsenal.renderHud()')
        A.evaluate('BB.game.boss.hp = 1')
        ok = wait(lambda: A.evaluate('BB.game.arsenal.charges.join()') == 'true,true,true', 20)
        check('al vencer al boss se recargan las 3', ok)
        wait(lambda: st(A) == 'LEVEL_COMPLETE', 20)
        # probar todas las armas (sin errores)
        A.click('#btn-next'); A.wait_for_timeout(1500)
        A.evaluate('BB.game.shields = 99')
        wait(lambda: A.evaluate('BB.game.meteors.countAlive()') > 0, 15)
        for wid in ['nova', 'rain', 'beam', 'swarm', 'overload', 'cryo', 'gravity', 'hole', 'emp', 'slowmo', 'dome', 'mirror', 'repair', 'jump', 'magnet', 'loot']:
            A.evaluate("BB.game.arsenal.fire('%s', 3)" % wid)
            A.wait_for_timeout(350)
        A.wait_for_timeout(2500)
        A.screenshot(path=OUT + '/a6_all.png')
        check('las 16 armas funcionan sin errores', not A.evaluate('BB.errors.length'), A.evaluate('BB.errors.map(e=>e.where+": "+e.msg).slice(0,4)'))
        check('Tiempo Bala frena a los enemigos', A.evaluate('BB.game.arsenal.enemyScale()') < 1)
        # cobrar -> ranking
        A.evaluate('BB.game.score = 50000; BB.game.cashOut()'); A.wait_for_timeout(500)
        check('récord de recorrido guardado', A.evaluate('BB.game.save.data.stats.bestRun') == 50000)
        # --- ranking ---
        A.click('#btn-rank'); A.wait_for_timeout(500)
        check('primera vez: pide ubicación y sugiere Argentina por la zona horaria', A.is_visible('#loc-modal') and A.evaluate("document.getElementById('loc-country').value") == 'AR')
        A.screenshot(path=OUT + '/a7_loc.png')
        A.select_option('#loc-city', 'Córdoba')
        A.click('#loc-save'); A.wait_for_timeout(1200)
        docs = A.evaluate('[...window.__mockDocs.entries()].filter(([k,v])=>v).map(([k])=>k.split("/").slice(0,2).join("/"))')
        check('sube a los 4 rankings (global, continente, país, ciudad)', all(x in docs for x in ['rk/g', 'rk/c-SA', 'rk/p-AR', 'rk/y-AR-cordoba']), docs)
        check('aparece en el top global', '50.000' in A.inner_text('#rank-list'))
        A.screenshot(path=OUT + '/a8_rank.png')
        # segundo jugador en otra ciudad
        B = mk()
        B.evaluate("BB.game.save.data.profile = {country:'AR', city:'Rosario', cont:'SA'}; BB.game.save.data.stats.bestRun = 0")
        B.evaluate('BB.game.startRun(1); BB.game.score = 70000; BB.game.cashOut()'); B.wait_for_timeout(800)
        A.wait_for_timeout(800)
        check('global: el de más puntaje arriba', A.evaluate('BB.game.rank.rows.map(r=>r.score).join()') == '70000,50000', A.evaluate('BB.game.rank.rows.map(r=>r.score).join()'))
        A.click('#rank-tabs button[data-sc="y"]'); A.wait_for_timeout(600)
        check('ciudad: solo Córdoba', A.evaluate('BB.game.rank.rows.map(r=>r.score).join()') == '50000' and A.evaluate('BB.game.rank.myPos') == 1)
        A.click('#rank-tabs button[data-sc="p"]'); A.wait_for_timeout(600)
        check('país: los dos (Argentina)', len(A.evaluate('BB.game.rank.rows')) == 2 and A.evaluate('BB.game.rank.myPos') == 2)
        A.screenshot(path=OUT + '/a9_rank_pais.png')
        A.click('#rank-loc'); A.wait_for_timeout(300)
        check('la ubicación no se puede volver a cambiar enseguida (30 días)', not A.is_visible('#loc-modal') and A.is_visible('#rank-note'))
        A.click('#btn-records'); A.wait_for_timeout(300)
        check('MIS RÉCORDS desde el ranking', A.is_visible('#s-records'))
        # duelo: sin arsenal
        A.click('#rec-back'); A.wait_for_timeout(200); A.click('#rank-back'); A.wait_for_timeout(200)
        A.evaluate('BB.game.pvp.startBot ? BB.game.pvp.startBot() : null'); A.wait_for_timeout(1500)
        if st(A) in ('PVP',):
            check('en el duelo no hay arsenal', not A.is_visible('#h-arsenal'))
        check('sin errores JS', not errs and not A.evaluate('BB.errors.length'), (errs[:3], A.evaluate('BB.errors.map(e=>e.where+": "+e.msg).slice(0,3)')))
        b.close()
    srv.shutdown()
    fails = [r for r in RESULTS if not r[1]]
    print('\n%d/%d OK' % (len(RESULTS) - len(fails), len(RESULTS)))

if __name__ == '__main__':
    main()
