"""COPA SEMANAL: nave aparte, Monedas Lunares, niveles de 6 s, 3 partidas por día, cuenta la última, ranking compartido.
Uso: python3 test/cup.py"""
import os, sys, time
from playwright.sync_api import sync_playwright
sys.path.insert(0, os.path.dirname(__file__))
from smoke import OUT, ARGS
from pvp import serve, st, wait, MOCK, check, RESULTS

def die(p):
    p.evaluate('BB.game.boosts.consume("shield"); BB.game.shields = 1; BB.game.player.invuln = 0; BB.game.hitPlayer("test")')
    return wait(lambda: p.is_visible('#s-cupres'), 12)

def main():
    srv = serve()
    url = 'http://127.0.0.1:%d/index.html' % srv.server_address[1]
    with sync_playwright() as pw:
        b = pw.chromium.launch(args=ARGS)
        ctx = b.new_context(viewport={'width': 390, 'height': 844}, is_mobile=True, has_touch=True)
        ctx.add_init_script(MOCK)
        errs = []
        def mk():
            p = ctx.new_page()
            p.on('pageerror', lambda e: errs.append(str(e)))
            p.goto(url)
            p.wait_for_function('window.__BB_READY === true', timeout=30000)
            p.click('#btn-start'); p.wait_for_timeout(300)
            return p
        A = mk()
        check('menú: JUGAR, COPA SEMANAL y DUELO (sin MOBA)', A.is_visible('#btn-play') and A.is_visible('#btn-cup') and A.is_visible('#btn-pvp') and A.query_selector('#btn-team') is None)
        check('chip de Monedas Lunares en 0', A.inner_text('#m-ml') == '0')
        A.evaluate('BB.game.save.data.coins = 99999')
        A.click('#btn-cup'); A.wait_for_timeout(500)
        check('pantalla de copa con cuenta regresiva y premios', A.is_visible('#s-cup') and A.inner_text('#cup-close') != '—' and 'USD 40' in A.inner_text('#cup-body') and 'USD 10' in A.inner_text('#cup-body'))
        check('modo prueba visible', A.is_visible('#cup-test'))
        check('3 partidas disponibles hoy', '3/3' in A.inner_text('#cup-me'))
        A.screenshot(path=OUT + '/c1_cup.png')
        # mejoras solo con ML (las monedas de campaña no sirven)
        A.click('button[data-tab="up"]'); A.wait_for_timeout(200)
        A.click('button[data-up="power"]'); A.wait_for_timeout(300)
        check('sin ML no se puede mejorar (aunque tengas monedas de campaña)', A.evaluate('BB.game.cup.data.up.power || 0') == 0 and A.evaluate('BB.game.save.data.coins') == 99999)
        check('te lleva a comprar Monedas Lunares', A.evaluate('BB.game.cup.tab') == 'ml' and 'USD 1' in A.inner_text('#cup-body'))
        A.screenshot(path=OUT + '/c2_packs.png')
        A.click('button[data-pack="p1"]'); A.wait_for_timeout(200)
        check('confirmación de compra (prueba, sin cobro)', A.is_visible('#cup-modal') and 'PRUEBA' in A.inner_text('#cup-modal'))
        A.click('#cup-confirm'); A.wait_for_timeout(300)
        check('USD 1 = 300 ML', A.evaluate('BB.game.cup.data.ml') == 300)
        A.click('button[data-tab="up"]'); A.wait_for_timeout(200)
        A.click('button[data-up="power"]'); A.wait_for_timeout(200)
        check('mejora de Potencia cuesta 120 ML', A.evaluate('BB.game.cup.data.ml') == 180 and A.evaluate('BB.game.cup.data.up.power') == 1)
        A.screenshot(path=OUT + '/c3_upgrades.png')
        camp_dmg = A.evaluate('BB.game.shop.computeStats().dmg')
        # partida 1
        A.click('#cup-play'); A.wait_for_timeout(600)
        check('copa arranca con la nave de copa', st(A) == 'PLAYING' and A.evaluate('BB.game.cupMode') and abs(A.evaluate('BB.game.stats.dmg') - 1.15) < 1e-6)
        check('contador de 6 s en pantalla', A.is_visible('#cup-hud') and A.inner_text('#ch-n') in '123456')
        A.evaluate('BB.game.shields = 99')
        L1 = A.evaluate('BB.game.level.num')
        ok = wait(lambda: A.evaluate('BB.game.cup.stage') >= 2, 25)
        check('al llegar a 6 arranca el nivel siguiente, más difícil', ok and A.evaluate('BB.game.level.num') > L1 and A.evaluate('BB.game.level.cfg.hpScale') > 1.2, (A.evaluate('BB.game.cup.stage'), A.evaluate('BB.game.level.num')))
        A.screenshot(path=OUT + '/c4_play.png')
        ok = wait(lambda: A.evaluate('BB.game.cup.stage') >= 3, 25)
        check('sigue subiendo de nivel', ok)
        check('en la copa las monedas no van a la billetera', A.evaluate('BB.game.save.data.coins') == 99999)
        # BOSS cada 5 niveles
        A.evaluate('BB.game.cup.stage = 4; BB.game.cup.stageT = 5.9')
        ok = wait(lambda: st(A) in ('BOSS_INTRO', 'BOSS_FIGHT') and A.evaluate('!!BB.game.boss'), 15)
        check('nivel 5 de copa = BOSS', ok and A.evaluate('BB.game.cup.stage') == 5 and A.evaluate('BB.game.cup.bossStage'), st(A))
        check('HUD muestra BOSS y el contador se frena', A.inner_text('#ch-n') == 'BOSS')
        check('boss de copa más fuerte (+20% vida)', A.evaluate('BB.game.boss.maxHp') > 0)
        wait(lambda: st(A) == 'BOSS_FIGHT', 15)
        A.wait_for_timeout(1500)
        A.screenshot(path=OUT + '/c4b_boss.png')
        t0 = A.evaluate('BB.game.cup.stageT')
        A.wait_for_timeout(1500)
        check('durante el boss no corre el contador', A.evaluate('BB.game.cup.stageT') == t0 and A.evaluate('BB.game.cup.stage') == 5)
        sc0 = A.evaluate('BB.game.score')
        A.evaluate('BB.game.shields = 2; BB.game.boss.hp = 1')
        ok = wait(lambda: A.evaluate('BB.game.cup.stage') == 6 and st(A) == 'PLAYING', 25)
        check('vencer al boss: sigue al nivel 6 con puntos y +1 escudo', ok and A.evaluate('BB.game.score') > sc0 + 10000 and A.evaluate('BB.game.shields') == 3, (A.evaluate('BB.game.cup.stage'), st(A), A.evaluate('BB.game.shields')))
        check('vuelve el contador de 6 s', A.inner_text('#ch-n') in '123456' and not A.evaluate('BB.game.cup.bossStage'))
        A.evaluate('BB.game.shields = 99')
        s1 = A.evaluate('BB.game.score')
        check('resultado al perder', die(A), st(A))
        A.screenshot(path=OUT + '/c5_result.png')
        last1 = A.evaluate('BB.game.cup.myLast().score')
        check('queda grabado el puntaje de la partida', last1 >= s1 > 0, (last1, s1))
        check('se sube al ranking compartido', A.evaluate('[...window.__mockDocs.values()].some(d => d.score === %d && d.final)' % last1))
        check('quedan 2 partidas hoy', A.evaluate('BB.game.cup.triesLeft()') == 2 and 'ARRIESGAR (2' in A.inner_text('#cr-retry'))
        # otro jugador ve el ranking
        B = mk()
        B.click('#btn-cup'); B.wait_for_timeout(1200)
        check('otro jugador ve el puntaje en el ranking', B.evaluate('BB.game.cup.board.length') >= 1 and ('%s' % '{:,}'.format(last1).replace(',', '.')) in B.inner_text('#cup-body'))
        B.screenshot(path=OUT + '/c6_rankB.png')
        # volver a jugar: aviso de reemplazo
        A.click('#cr-retry'); A.wait_for_timeout(500)
        check('aviso: jugar de nuevo reemplaza tu puntaje', A.is_visible('#cup-modal') and 'reemplaza' in A.inner_text('#cup-modal') and 'ME PLANTO' in A.inner_text('#cup-cancel'))
        A.screenshot(path=OUT + '/c7_confirm.png')
        A.click('#cup-cancel'); A.wait_for_timeout(300)
        check('plantarse no gasta partida', A.evaluate('BB.game.cup.triesLeft()') == 2 and A.evaluate('BB.game.cup.myLast().score') == last1)
        A.click('#cup-play'); A.wait_for_timeout(300); A.click('#cup-confirm'); A.wait_for_timeout(600)
        check('partida 2 arranca', A.evaluate('BB.game.cupMode') and A.evaluate('BB.game.cup.triesLeft()') == 1)
        check('al empezar, el ranking ya no muestra el puntaje anterior', A.evaluate('BB.game.cup.myLast().score') == 0)
        A.wait_for_timeout(800)
        A.evaluate('BB.game.score = 100')
        die(A)
        last2 = A.evaluate('BB.game.cup.myLast().score')
        check('cuenta la ÚLTIMA partida aunque sea menor', last2 < last1, (last2, last1))
        # partida 3 abandonada desde pausa: cuenta lo hecho
        A.click('#cr-retry'); A.wait_for_timeout(300); A.click('#cup-confirm'); A.wait_for_timeout(600)
        A.evaluate('BB.game.score = 777')
        A.click('#btn-pause'); A.wait_for_timeout(200)
        check('pausa avisa que termina la partida', 'TERMINAR' in A.inner_text('#btn-quit'))
        A.click('#btn-quit'); A.wait_for_timeout(600)
        check('abandonar: queda el puntaje hecho', A.evaluate('BB.game.cup.myLast().score') == 777 and st(A) == 'MENU')
        A.click('#btn-cup'); A.wait_for_timeout(400)
        check('sin partidas: botón bloqueado hasta mañana', A.evaluate('BB.game.cup.triesLeft()') == 0 and 'SIN PARTIDAS' in A.inner_text('#cup-play'))
        A.click('#cup-play'); A.wait_for_timeout(300)
        check('no deja jugar una 4.ª vez', not A.evaluate('BB.game.cupMode') and A.is_visible('#cup-note'))
        A.screenshot(path=OUT + '/c8_notries.png')
        # campaña intacta
        A.click('#cup-back'); A.wait_for_timeout(300)
        A.click('#btn-play'); A.wait_for_timeout(600)
        check('campaña usa sus propias mejoras', abs(A.evaluate('BB.game.stats.dmg') - camp_dmg) < 1e-6 and not A.evaluate('BB.game.cupMode') and A.evaluate('BB.game.inCampaign'))
        check('sin errores JS', not errs and not A.evaluate('BB.errors.length'), (errs[:3], A.evaluate('BB.errors.map(e=>e.where+": "+e.msg).slice(0,3)')))
        b.close()
    srv.shutdown()
    fails = [r for r in RESULTS if not r[1]]
    print('\n%d/%d OK' % (len(RESULTS) - len(fails), len(RESULTS)))

if __name__ == '__main__':
    main()
